#!/bin/sh
if [ ! -f "`command -v pycodestyle-3`" ]; then
  echo "You must install the python3-pycodestyle package before using the quality script."
  exit 1
fi
rm err.txt
if [ -f "`command -v outputinspector`" ]; then
  pycodestyle-3 __init__.py > err.txt
  # For one-liner, would use `||` not `&&`, because pycodestyle-3 returns nonzero (error state) if there are any errors
  outputinspector
else
  pycodestyle-3 __init__.py
  echo
  echo "If you install outputinspector, this output can be examined automatically, allowing double-click to skip to line in Geany/Kate"
  echo
fi
